/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baikiemtragiuaky;

import java.io.File;
import java.io.IOException;
import java.net.ConnectException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kiet
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSPM1 = new javax.swing.JButton();
        btnSPM2 = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnKHM1 = new javax.swing.JButton();
        btnKHM2 = new javax.swing.JButton();
        btnKHOM1 = new javax.swing.JButton();
        javax.swing.JButton btnKHOM2 = new javax.swing.JButton();
        btnHDM1 = new javax.swing.JButton();
        btnHDM2 = new javax.swing.JButton();
        btnCTHDM1 = new javax.swing.JButton();
        btnCTHDM2 = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnKhoHang = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnChiTietHoaDon = new javax.swing.JButton();
        goPMD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SANPHAM");

        btnSPM1.setText("MANH 1");
        btnSPM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPM1ActionPerformed(evt);
            }
        });

        btnSPM2.setText("MANH 2");
        btnSPM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPM2ActionPerformed(evt);
            }
        });

        btnSanPham.setText("SAN PHAM");
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        txtError.setColumns(20);
        txtError.setRows(5);
        jScrollPane1.setViewportView(txtError);

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblResult);

        jLabel2.setText("KHACHHANG");

        jLabel3.setText("KHOHANG");

        jLabel4.setText("HOADON");

        jLabel5.setText("CHITIETHOADON");

        btnKHM1.setText("MANH 1");
        btnKHM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHM1ActionPerformed(evt);
            }
        });

        btnKHM2.setText("MANH 2");
        btnKHM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHM2ActionPerformed(evt);
            }
        });

        btnKHOM1.setText("MANH 1");
        btnKHOM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHOM1ActionPerformed(evt);
            }
        });

        btnKHOM2.setText("MANH 2");
        btnKHOM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHOM2ActionPerformed(evt);
            }
        });

        btnHDM1.setText("MANH 1");
        btnHDM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDM1ActionPerformed(evt);
            }
        });

        btnHDM2.setText("MANH 2");
        btnHDM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDM2ActionPerformed(evt);
            }
        });

        btnCTHDM1.setText("MANH 1");
        btnCTHDM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTHDM1ActionPerformed(evt);
            }
        });

        btnCTHDM2.setText("MANH 2");
        btnCTHDM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTHDM2ActionPerformed(evt);
            }
        });

        btnKhachHang.setText("KHACHHANG");
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnKhoHang.setText("KHOHANG");
        btnKhoHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoHangActionPerformed(evt);
            }
        });

        btnHoaDon.setText("HOADON");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnChiTietHoaDon.setText("CHITIETHOADON");
        btnChiTietHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietHoaDonActionPerformed(evt);
            }
        });

        goPMD.setText("PhanManhDoc");
        goPMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goPMDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSPM1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSPM2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKHM1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKHM2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKHOM1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKHOM2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHDM1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHDM2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCTHDM1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCTHDM2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnKhachHang)
                                    .addComponent(btnKhoHang)
                                    .addComponent(btnSanPham))
                                .addGap(16, 16, 16))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(btnHoaDon)
                                    .addGap(38, 38, 38))
                                .addComponent(btnChiTietHoaDon, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(46, 46, 46)
                        .addComponent(goPMD)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSPM1)
                    .addComponent(btnSPM2)
                    .addComponent(btnSanPham))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnKHM1)
                    .addComponent(btnKHM2)
                    .addComponent(btnKhachHang))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnKHOM1)
                    .addComponent(btnKHOM2)
                    .addComponent(btnKhoHang)
                    .addComponent(goPMD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnHDM1)
                    .addComponent(btnHDM2)
                    .addComponent(btnHoaDon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnCTHDM1)
                    .addComponent(btnCTHDM2)
                    .addComponent(btnChiTietHoaDon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSPM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPM2ActionPerformed
//        Phân mảnh ngang
        File f = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MASANPHAM", "TENSANPHAM", "GIABAN", "MAKHOHANG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataSanPham(f, tblmodel, tblResult, txtError, tenCot, "2");


    }//GEN-LAST:event_btnSPM2ActionPerformed

    private void btnSPM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPM1ActionPerformed
        // Phân mảnh ngang
        File f = new File("D:\\Download\\Data\\server_1.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MASANPHAM", "TENSANPHAM", "GIABAN", "MAKHOHANG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataSanPham(f, tblmodel, tblResult, txtError, tenCot, "1");

    }//GEN-LAST:event_btnSPM1ActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        File f1 = new File("D:\\Download\\Data\\server_1.txt");
        File f2 = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MASANPHAM", "TENSANPHAM", "GIABAN", "MAKHOHANG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataSanPham(f1, tblmodel, tblResult, txtError, tenCot, "1");
        db.getDataSanPham(f2, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnKHM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHM1ActionPerformed
        File f = new File("D:\\Download\\Data\\server_1.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAKHACHHANG", "TENKH", "DIACHI", "SODIENTHOAI", "LOAIKHACHHANG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataKhachHang(f, tblmodel, tblResult, txtError, tenCot, "1");
    }//GEN-LAST:event_btnKHM1ActionPerformed

    private void btnKHM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHM2ActionPerformed
        File f = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAKHACHHANG", "TENKH", "DIACHI", "SODIENTHOAI", "LOAIKHACHHANG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataKhachHang(f, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnKHM2ActionPerformed

    private void btnKHOM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHOM1ActionPerformed
        File f = new File("D:\\Download\\Data\\server_1.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAKHOHANG", "TENKHOHANG", "DIACHI"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataKhoHang(f, tblmodel, tblResult, txtError, tenCot, "1");
    }//GEN-LAST:event_btnKHOM1ActionPerformed

    private void btnKHOM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHOM2ActionPerformed
        File f = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAKHOHANG", "TENKHOHANG", "DIACHI"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataKhoHang(f, tblmodel, tblResult, txtError, tenCot, "2");

    }//GEN-LAST:event_btnKHOM2ActionPerformed

    private void btnHDM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDM1ActionPerformed
        File f = new File("D:\\Download\\Data\\server_1.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAHOADON", "MAKHACHHANG", "NGAY"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataHoaDon(f, tblmodel, tblResult, txtError, tenCot, "1");
    }//GEN-LAST:event_btnHDM1ActionPerformed

    private void btnHDM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDM2ActionPerformed
        File f = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAHOADON", "MAKHACHHANG", "NGAY"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataHoaDon(f, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnHDM2ActionPerformed

    private void btnCTHDM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTHDM1ActionPerformed
        File f = new File("D:\\Download\\Data\\server_1.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAHOADON", "MASANPHAM", "SOLUONG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataChiTietHoaDon(f, tblmodel, tblResult, txtError, tenCot, "1");
    }//GEN-LAST:event_btnCTHDM1ActionPerformed

    private void btnCTHDM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTHDM2ActionPerformed
        File f = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAHOADON", "MASANPHAM", "SOLUONG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataChiTietHoaDon(f, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnCTHDM2ActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        File f1 = new File("D:\\Download\\Data\\server_1.txt");
        File f2 = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAKHACHHANG", "TENKH", "DIACHI", "SODIENTHOAI", "LOAIKHACHHANG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataKhachHang(f1, tblmodel, tblResult, txtError, tenCot, "1");
        db.getDataKhachHang(f2, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnKhoHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoHangActionPerformed
        File f1 = new File("D:\\Download\\Data\\server_1.txt");
        File f2 = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAKHOHANG", "TENKHOHANG", "DIACHI"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataKhoHang(f1, tblmodel, tblResult, txtError, tenCot, "1");
        db.getDataKhoHang(f2, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnKhoHangActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        File f1 = new File("D:\\Download\\Data\\server_1.txt");
        File f2 = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAHOADON", "MAKHACHHANG", "NGAY"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataHoaDon(f1, tblmodel, tblResult, txtError, tenCot, "1");
        db.getDataHoaDon(f2, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnChiTietHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietHoaDonActionPerformed
        File f1 = new File("D:\\Download\\Data\\server_1.txt");
        File f2 = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAHOADON", "MASANPHAM", "SOLUONG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataChiTietHoaDon(f1, tblmodel, tblResult, txtError, tenCot, "1");
        db.getDataChiTietHoaDon(f2, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnChiTietHoaDonActionPerformed

    private void goPMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goPMDActionPerformed
        PhanManhDoc PhanManhDocFrame = new PhanManhDoc();
        PhanManhDocFrame.setVisible(true); // Hiển thị JFrame mới
        this.dispose(); // Đóng JFrame hiện tại
    }//GEN-LAST:event_goPMDActionPerformed

    /**
     * @param args the command line arguments
     */
    private DefaultTableModel tblmodel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCTHDM1;
    private javax.swing.JButton btnCTHDM2;
    private javax.swing.JButton btnChiTietHoaDon;
    private javax.swing.JButton btnHDM1;
    private javax.swing.JButton btnHDM2;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKHM1;
    private javax.swing.JButton btnKHM2;
    private javax.swing.JButton btnKHOM1;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnKhoHang;
    private javax.swing.JButton btnSPM1;
    private javax.swing.JButton btnSPM2;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton goPMD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextArea txtError;
    // End of variables declaration//GEN-END:variables
}
