/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baikiemtragiuaky;

import java.io.File;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kiet
 */
public class PhanManhDoc extends javax.swing.JFrame {

    /**
     * Creates new form PhanManhDoc
     */
    public PhanManhDoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSPDM1 = new javax.swing.JButton();
        btnSPDM2 = new javax.swing.JButton();
        btnKHDM2 = new javax.swing.JButton();
        btnKHDM1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnKhoDM2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnKhoDM1 = new javax.swing.JButton();
        btnHDDM2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnHDDM1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCTHDDM2 = new javax.swing.JButton();
        btnCTHDDM1 = new javax.swing.JButton();
        btnSPD = new javax.swing.JButton();
        btnKHD = new javax.swing.JButton();
        btnKhoD = new javax.swing.JButton();
        btnHDD = new javax.swing.JButton();
        btnCTHDD = new javax.swing.JButton();
        btnGoPMN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SANPHAM");

        btnSPDM1.setText("MANH1");
        btnSPDM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPDM1(evt);
            }
        });

        btnSPDM2.setText("MANH2");
        btnSPDM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPDM2(evt);
            }
        });

        btnKHDM2.setText("MANH2");
        btnKHDM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHDM2(evt);
            }
        });

        btnKHDM1.setText("MANH1");
        btnKHDM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHDM1(evt);
            }
        });

        jLabel2.setText("KHACHHANG");

        btnKhoDM2.setText("MANH2");
        btnKhoDM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoDM2(evt);
            }
        });

        jLabel3.setText("KHOHANG");

        btnKhoDM1.setText("MANH1");
        btnKhoDM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoDM1(evt);
            }
        });

        btnHDDM2.setText("MANH2");
        btnHDDM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDDM2(evt);
            }
        });

        jLabel4.setText("HOADON");

        btnHDDM1.setText("MANH1");
        btnHDDM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDDM1(evt);
            }
        });

        jLabel5.setText("CHITIETHOADON");

        btnCTHDDM2.setText("MANH2");
        btnCTHDDM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTHDDM2(evt);
            }
        });

        btnCTHDDM1.setText("MANH1");
        btnCTHDDM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTHDDM1(evt);
            }
        });

        btnSPD.setText("SANPHAM");
        btnSPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPD(evt);
            }
        });

        btnKHD.setText("KHACHHANG");
        btnKHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHD(evt);
            }
        });

        btnKhoD.setText("KHOHANG");
        btnKhoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoD(evt);
            }
        });

        btnHDD.setText("HOADON");
        btnHDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDD(evt);
            }
        });

        btnCTHDD.setText("CHITIETHOADON");
        btnCTHDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTHDD(evt);
            }
        });

        btnGoPMN.setText("PMNGANG");
        btnGoPMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoPMN(evt);
            }
        });

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        txtError.setColumns(20);
        txtError.setRows(5);
        jScrollPane2.setViewportView(txtError);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSPDM1)
                        .addGap(18, 18, 18)
                        .addComponent(btnSPDM2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKHDM1)
                        .addGap(18, 18, 18)
                        .addComponent(btnKHDM2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKhoDM1)
                        .addGap(18, 18, 18)
                        .addComponent(btnKhoDM2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHDDM1)
                        .addGap(18, 18, 18)
                        .addComponent(btnHDDM2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCTHDDM1)
                        .addGap(18, 18, 18)
                        .addComponent(btnCTHDDM2)))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCTHDD)
                            .addComponent(btnHDD)
                            .addComponent(btnKhoD)
                            .addComponent(btnKHD))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSPD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGoPMN)
                        .addGap(16, 16, 16))))
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSPDM1)
                    .addComponent(btnSPDM2)
                    .addComponent(btnSPD)
                    .addComponent(btnGoPMN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnKHDM1)
                    .addComponent(btnKHDM2)
                    .addComponent(btnKHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnKhoDM1)
                            .addComponent(btnKhoDM2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btnHDDM1)
                            .addComponent(btnHDDM2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKhoD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHDD)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(btnCTHDDM1)
                        .addComponent(btnCTHDDM2))
                    .addComponent(btnCTHDD))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSPDM1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPDM1
        // TODO add your handling code here:
        File f = new File("D:\\Download\\Data\\server_1.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MASANPHAM", "TENSANPHAM"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataSanPhamManh(f, tblmodel, tblResult, txtError, tenCot, "1");
    }//GEN-LAST:event_btnSPDM1

    private void btnSPDM2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPDM2
        // TODO add your handling code here:
        File f = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MASANPHAM", "GIABAN", "MAKHOHANG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataSanPhamManh(f, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnSPDM2

    private void btnKHDM2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHDM2
        // TODO add your handling code here:
        File f = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAKHACHHANG", "TENKH", "DIACHI"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataKhachHangManh(f, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnKHDM2

    private void btnKHDM1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHDM1
        // TODO add your handling code here:
        File f = new File("D:\\Download\\Data\\server_1.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAKHACHHANG", "SODIENTHOAI", "LOAIKHACHHANG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataKhachHangManh(f, tblmodel, tblResult, txtError, tenCot, "1");
    }//GEN-LAST:event_btnKHDM1

    private void btnKhoDM2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoDM2
        // TODO add your handling code here:
        File f = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAKHOHANG", "DIACHI"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataKhoHangManh(f, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnKhoDM2

    private void btnKhoDM1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoDM1
        // TODO add your handling code here:
        File f = new File("D:\\Download\\Data\\server_1.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAKHOHANG", "TENKHOHANG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataKhoHangManh(f, tblmodel, tblResult, txtError, tenCot, "1");
    }//GEN-LAST:event_btnKhoDM1

    private void btnHDDM2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDDM2
        // TODO add your handling code here:
        File f = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAHOADON", "MAKHACHHANG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataHoaDonManh(f, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnHDDM2

    private void btnHDDM1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDDM1
        // TODO add your handling code here:
        File f = new File("D:\\Download\\Data\\server_1.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAHOADON", "NGAY"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataHoaDonManh(f, tblmodel, tblResult, txtError, tenCot, "1");
    }//GEN-LAST:event_btnHDDM1

    private void btnCTHDDM2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTHDDM2
        // TODO add your handling code here:
        File f = new File("D:\\Download\\Data\\server_2.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAHOADON", "MASANPHAM"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataCTHoaDonManh(f, tblmodel, tblResult, txtError, tenCot, "2");
    }//GEN-LAST:event_btnCTHDDM2

    private void btnCTHDDM1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTHDDM1
        // TODO add your handling code here:
        File f = new File("D:\\Download\\Data\\server_1.txt");
        DataModel db = new DataModel();
        String tenCot[] = {"MAHOADON", "SOLUONG"};
        tblmodel = new DefaultTableModel(tenCot, 0);
        db.getDataCTHoaDonManh(f, tblmodel, tblResult, txtError, tenCot, "1");
    }//GEN-LAST:event_btnCTHDDM1

    private void btnSPD(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPD
        // TODO add your handling code here:
        DataModel db = new DataModel();
        String tenCot[] = {"MASANPHAM", "TENSANPHAM", "GIABAN", "MAKHOHANG"};

        File f = new File("D:\\Download\\Data\\server_1.txt");
        ArrayList<ArrayList<String>> a = db.getManhSanPham(f, tblmodel, tblResult, txtError, tenCot, "1");

        f = new File("D:\\Download\\Data\\server_2.txt");
        ArrayList<ArrayList<String>> b = db.getManhSanPham(f, tblmodel, tblResult, txtError, tenCot, "2");

        // Check if both a and b have data
        ArrayList<ArrayList<String>> c = db.ket(a, b);
        tblmodel = db.getTableModel(tenCot, c);
        tblResult.setModel(tblmodel);

    }//GEN-LAST:event_btnSPD

    private void btnKHD(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHD
        // TODO add your handling code here:
        DataModel db = new DataModel();
        String tenCot[] = {"MAKHACHHANG", "SODIENTHOAI", "LOAIKHACHHANG","TENKH", "DIACHI", };

        File f = new File("D:\\Download\\Data\\server_1.txt");
        ArrayList<ArrayList<String>> a = db.getManhKhachHang(f, tblmodel, tblResult, txtError, tenCot, "1");

        f = new File("D:\\Download\\Data\\server_2.txt");
        ArrayList<ArrayList<String>> b = db.getManhKhachHang(f, tblmodel, tblResult, txtError, tenCot, "2");

        // Check if both a and b have data
        ArrayList<ArrayList<String>> c = db.ket(a, b);
        tblmodel = db.getTableModel(tenCot, c);
        tblResult.setModel(tblmodel);
    }//GEN-LAST:event_btnKHD

    private void btnKhoD(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoD
        // TODO add your handling code here:
        DataModel db = new DataModel();
        String tenCot[] = {"MAKHOHANG", "TENKHOHANG", "DIACHI"};

        File f = new File("D:\\Download\\Data\\server_1.txt");
        ArrayList<ArrayList<String>> a = db.getManhKhoHang(f, tblmodel, tblResult, txtError, tenCot, "1");

        f = new File("D:\\Download\\Data\\server_2.txt");
        ArrayList<ArrayList<String>> b = db.getManhKhoHang(f, tblmodel, tblResult, txtError, tenCot, "2");

        // Check if both a and b have data
        ArrayList<ArrayList<String>> c = db.ket(a, b);
        tblmodel = db.getTableModel(tenCot, c);
        tblResult.setModel(tblmodel);
    }//GEN-LAST:event_btnKhoD

    private void btnHDD(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDD
        // TODO add your handling code here:
        DataModel db = new DataModel();
        String tenCot[] = {"MAHOADON", "NGAY", "MAKHACHHANG"};

        File f = new File("D:\\Download\\Data\\server_1.txt");
        ArrayList<ArrayList<String>> a = db.getManhHoaDon(f, tblmodel, tblResult, txtError, tenCot, "1");

        f = new File("D:\\Download\\Data\\server_2.txt");
        ArrayList<ArrayList<String>> b = db.getManhHoaDon(f, tblmodel, tblResult, txtError, tenCot, "2");

        // Check if both a and b have data
        ArrayList<ArrayList<String>> c = db.ket(a, b);
        tblmodel = db.getTableModel(tenCot, c);
        tblResult.setModel(tblmodel);
    }//GEN-LAST:event_btnHDD

    private void btnCTHDD(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTHDD
        // TODO add your handling code here:
        DataModel db = new DataModel();
        String tenCot[] = {"MAHOADON", "SOLUONG", "MASANPHAM"};

        File f = new File("D:\\Download\\Data\\server_1.txt");
        ArrayList<ArrayList<String>> a = db.getManhCTHoaDon(f, tblmodel, tblResult, txtError, tenCot, "1");

        f = new File("D:\\Download\\Data\\server_2.txt");
        ArrayList<ArrayList<String>> b = db.getManhCTHoaDon(f, tblmodel, tblResult, txtError, tenCot, "2");

        // Check if both a and b have data
        ArrayList<ArrayList<String>> c = db.ket(a, b);
        tblmodel = db.getTableModel(tenCot, c);
        tblResult.setModel(tblmodel);
    }//GEN-LAST:event_btnCTHDD

    private void btnGoPMN(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoPMN
        // TODO add your handling code here:
        GiaoDienChinh giaoDienChinhFrame = new GiaoDienChinh();
        giaoDienChinhFrame.setVisible(true); // Hiển thị JFrame mới
        this.dispose(); // Đóng JFrame hiện tại
    }//GEN-LAST:event_btnGoPMN

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhanManhDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhanManhDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhanManhDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhanManhDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhanManhDoc().setVisible(true);
            }
        });
    }
    private DefaultTableModel tblmodel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCTHDD;
    private javax.swing.JButton btnCTHDDM1;
    private javax.swing.JButton btnCTHDDM2;
    private javax.swing.JButton btnGoPMN;
    private javax.swing.JButton btnHDD;
    private javax.swing.JButton btnHDDM1;
    private javax.swing.JButton btnHDDM2;
    private javax.swing.JButton btnKHD;
    private javax.swing.JButton btnKHDM1;
    private javax.swing.JButton btnKHDM2;
    private javax.swing.JButton btnKhoD;
    private javax.swing.JButton btnKhoDM1;
    private javax.swing.JButton btnKhoDM2;
    private javax.swing.JButton btnSPD;
    private javax.swing.JButton btnSPDM1;
    private javax.swing.JButton btnSPDM2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextArea txtError;
    // End of variables declaration//GEN-END:variables
}
