USE CSDLPTTH01_BT1

-- SP
CREATE TABLE SANPHAM1 (
	MASANPHAM INT NOT NULL,
	TENSANPHAM NVARCHAR(100) NOT NULL,
	GIABAN INT,
	MAKHOHANG INT,
);
go

INSERT INTO SANPHAM1
SELECT * FROM SANPHAM WHERE GIABAN < 100000
go



-- KhachHang
CREATE TABLE KHACHHANG1 (
	MAKHACHHANG INT NOT NULL,
	TENKH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(200),
	SODIENTHOAI CHAR(10) NOT NULL,
	LOAIKHACHHANG NVARCHAR(10),
);
go

INSERT INTO KHACHHANG1
SELECT * FROM KHACHHANG WHERE LOAIKHACHHANG like N'Vàng'
go

-- KhoHang
CREATE TABLE KHOHANG1 (
    MAKHOHANG INT PRIMARY KEY,
    TENKHOHANG NVARCHAR(50),
    DIACHI NVARCHAR(200)
);

INSERT INTO KHOHANG1
SELECT * FROM KHOHANG WHERE TENKHOHANG LIKE N'%Bình Thạnh%' OR TENKHOHANG LIKE N'%Thủ Đức%'
go

-- HoaDon
CREATE TABLE HOADON1 (
	MAHOADON INT NOT NULL,
	MAKHACHHANG INT NOT NULL,
	NGAY DATETIME NOT NULL,
);

INSERT INTO HOADON1
SELECT * FROM HOADON1 WHERE MONTH(NGAY) < 2


go

DELETE FROM KHACHHANG 
WHERE LOAIKHACHHANG not like N'Vàng'
go

USE CSDLPTTH01_BT1
SELECT * FROM CHITIETHOADON
SELECT * FROM HOADON
SELECT * FROM SANPHAM
SELECT * FROM KHACHHANG
SELECT * FROM KHOHANG
SELECT * FROM KHOHANG1
SELECT * FROM SANPHAM
