USE CSDLPTTH01_BT1
GO

-- Sản phẩm 
CREATE TABLE SANPHAM_DOC_1(
	MASANPHAM INT,
	TENSANPHAM NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_SANPHAMM1 PRIMARY KEY (MASANPHAM))
GO
INSERT INTO SANPHAM_DOC_1 SELECT MASANPHAM ,TENSANPHAM FROM SANPHAM 
GO

CREATE TABLE SANPHAM_DOC_2(
	MASANPHAM int ,
	GIABAN INT,
	MAKHOHANG INT,
	CONSTRAINT PK_SANPHAM_DOC_2 PRIMARY KEY (MASANPHAM),
	CONSTRAINT FK_KHOHANG_DOC_2 FOREIGN KEY (MAKHOHANG) REFERENCES KHOHANG(MAKHOHANG)
)
GO
INSERT INTO SANPHAM_DOC_2 SELECT MASANPHAM ,GIABAN , MAKHOHANG FROM SANPHAM 

GO

-- Khách Hàng
CREATE TABLE KHACHHANG_DOC_1 (
	MAKHACHHANG INT NOT NULL,
	SODIENTHOAI CHAR(10) NOT NULL,
	LOAIKHACHHANG NVARCHAR(10),
	CONSTRAINT PK_KHACHHANG1 PRIMARY KEY (MAKHACHHANG)
);
GO
INSERT INTO KHACHHANG_DOC_1 SELECT MAKHACHHANG ,SODIENTHOAI , LOAIKHACHHANG FROM KHACHHANG 

CREATE TABLE KHACHHANG_DOC_2 (
	MAKHACHHANG INT NOT NULL,
	TENKH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(200),
	CONSTRAINT PK_KHACHHANG2 PRIMARY KEY (MAKHACHHANG)
);
GO
INSERT INTO KHACHHANG_DOC_2 SELECT MAKHACHHANG ,TENKH , DIACHI FROM KHACHHANG 


-- Kho Hàng
CREATE TABLE KHOHANG_DOC_1 (
    MAKHOHANG INT PRIMARY KEY,
    TENKHOHANG NVARCHAR(50),

);
GO
INSERT INTO KHOHANG_DOC_1 SELECT MAKHOHANG ,TENKHOHANG  FROM KHOHANG 

CREATE TABLE KHOHANG_DOC_2 (
    MAKHOHANG INT PRIMARY KEY,
    DIACHI NVARCHAR(200)
);
GO
INSERT INTO KHOHANG_DOC_2 SELECT MAKHOHANG, DIACHI FROM KHOHANG 

-- Hóa Đơn
CREATE TABLE HOADON_DOC_1 (
	MAHOADON INT NOT NULL,
	NGAY DATETIME NOT NULL,
	CONSTRAINT PK_HOADON_DOC_1 PRIMARY KEY (MAHOADON)
);
GO
INSERT INTO HOADON_DOC_1 SELECT MAHOADON ,NGAY  FROM HOADON 

GO
CREATE TABLE HOADON_DOC_2 (
	MAHOADON INT NOT NULL,
	MAKHACHHANG INT NOT NULL,
	CONSTRAINT PK_HOADON_DOC_2 PRIMARY KEY (MAHOADON),	CONSTRAINT FK_KHACHHANG_DOC_2 FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)

);
GO
INSERT INTO HOADON_DOC_2 SELECT MAHOADON, MAKHACHHANG FROM HOADON 
GO

-- CT Hóa Đơn
CREATE TABLE CHITIETHOADON_DOC_1 (
	MAHOADON INT NOT NULL,
	SOLUONG INT NOT NULL,

);
GO
INSERT INTO CHITIETHOADON_DOC_1 SELECT MAHOADON, SOLUONG FROM CHITIETHOADON 
GO

CREATE TABLE CHITIETHOADON_DOC_2 (
	MAHOADON INT NOT NULL,
	MASANPHAM INT NOT NULL,
	CONSTRAINT FK_SANPHAM_DOC_2 FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)

);
GO
INSERT INTO CHITIETHOADON_DOC_2 SELECT MAHOADON, MASANPHAM FROM CHITIETHOADON 
GO

SELECT * FROM CHITIETHOADON_DOC_1
SELECT * FROM CHITIETHOADON_DOC_2
SELECT * FROM HOADON_DOC_1
SELECT * FROM HOADON_DOC_2
SELECT * FROM SANPHAM_DOC_1
SELECT * FROM SANPHAM_DOC_2
SELECT * FROM KHACHHANG_DOC_1
SELECT * FROM KHACHHANG_DOC_2
SELECT * FROM KHOHANG_DOC_1
SELECT * FROM KHOHANG_DOC_2

DROP TABLE CHITIETHOADON_DOC_2;

SELECT HAS_PERMS_BY_NAME('dbo.CHITIETHOADON_DOC_2', 'OBJECT', 'DELETE');
SELECT * FROM sys.tables
