USE CSDLPTTH01_BT1

-- SP
CREATE TABLE SANPHAM1 (
	MASANPHAM INT NOT NULL,
	TENSANPHAM NVARCHAR(100) NOT NULL,
	GIABAN INT,
	MAKHOHANG INT,
);
go

INSERT INTO SANPHAM1
SELECT * FROM SANPHAM WHERE GIABAN < 100000
go





-- KhachHang
CREATE TABLE KHACHHANG1 (
	MAKHACHHANG INT NOT NULL,
	TENKH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(200),
	SODIENTHOAI CHAR(10) NOT NULL,
	LOAIKHACHHANG NVARCHAR(10),
);
go

INSERT INTO KHACHHANG1
SELECT * FROM KHACHHANG WHERE LOAIKHACHHANG like N'Vàng'
go



-- KhoHang
CREATE TABLE KHOHANG1 (
    MAKHOHANG INT PRIMARY KEY,
    TENKHOHANG NVARCHAR(50),
    DIACHI NVARCHAR(200)
);

INSERT INTO KHOHANG1
SELECT * FROM KHOHANG WHERE TENKHOHANG LIKE N'%Bình Thạnh%' OR TENKHOHANG LIKE N'%Thủ Đức%'
go



-- HoaDon
CREATE TABLE HOADON1 (
	MAHOADON INT NOT NULL,
	MAKHACHHANG INT NOT NULL,
	NGAY DATETIME NOT NULL,
);

INSERT INTO HOADON1
SELECT * FROM HOADON1 WHERE MONTH(NGAY) < 2

DROP TABLE HOADON1
go

-- HoaDon


-- ChiTietHoaDon
CREATE TABLE CHITIETHOADON1 (
	MAHOADON INT NOT NULL,
	MASANPHAM INT NOT NULL,
	SOLUONG INT NOT NULL,
);

INSERT INTO CHITIETHOADON1
SELECT * FROM CHITIETHOADON WHERE MAHOADON < 3


-- 


SELECT * FROM CHITIETHOADON1
SELECT * FROM HOADON1
SELECT * FROM SANPHAM1
SELECT * FROM KHACHHANG1
SELECT * FROM KHOHANG1


-- Phan manh 2
-- SP
CREATE TABLE SANPHAM2 (
	MASANPHAM INT NOT NULL,
	TENSANPHAM NVARCHAR(100) NOT NULL,
	GIABAN INT,
	MAKHOHANG INT,
);
go

INSERT INTO SANPHAM2
SELECT * FROM SANPHAM WHERE GIABAN >= 100000
go



-- KhachHang
CREATE TABLE KHACHHANG2 (
	MAKHACHHANG INT NOT NULL,
	TENKH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(200),
	SODIENTHOAI CHAR(10) NOT NULL,
	LOAIKHACHHANG NVARCHAR(10),
);
go

INSERT INTO KHACHHANG2
SELECT * FROM KHACHHANG WHERE LOAIKHACHHANG NOT like N'Vàng'
go

-- KhoHang
CREATE TABLE KHOHANG2 (
    MAKHOHANG INT PRIMARY KEY,
    TENKHOHANG NVARCHAR(50),
    DIACHI NVARCHAR(200)
);

INSERT INTO KHOHANG2
SELECT * FROM KHOHANG2 WHERE TENKHOHANG NOT LIKE N'%Bình Thạnh%' AND TENKHOHANG NOT LIKE N'%Thủ Đức%'
go

-- HoaDon
CREATE TABLE HOADON2 (
	MAHOADON INT NOT NULL,
	MAKHACHHANG INT NOT NULL,
	NGAY DATETIME NOT NULL,
);

INSERT INTO HOADON2
SELECT * FROM HOADON2 WHERE MONTH(NGAY) >= 2


go

-- ChiTietHoaDon
CREATE TABLE CHITIETHOADON2 (
	MAHOADON INT NOT NULL,
	MASANPHAM INT NOT NULL,
	SOLUONG INT NOT NULL,
);

INSERT INTO CHITIETHOADON2
SELECT * FROM CHITIETHOADON WHERE MAHOADON >= 3


-- 


SELECT * FROM CHITIETHOADON2
SELECT * FROM HOADON2
SELECT * FROM SANPHAM2
SELECT * FROM KHACHHANG2
SELECT * FROM KHOHANG2
